sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t hjun/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hjun/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app-practice"
  env: "Dockerreactapppractice-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-536067036996"
  bucket_path: "docker-react-app-practice"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
